### ISSUE TITLE
Clients don't automatically .close() on exit

### ISSUE THREAD

**Issue by thusoy** [honeycombio/libhoney-py#58]
`atexit` is currently used to wait for in-flight events to finish for the global client, but if you create your own client you have to explicitly call `.close()`. This seems inconsistent and was causing me some issues in short-lived scripts that submit events just before exit using a custom client.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
